# Generated by Django 4.2.2 on 2023-06-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricator_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('county_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.counties')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('indicative_forces', models.FloatField()),
                ('workers', models.IntegerField()),
                ('info', models.CharField(max_length=2000, null=True)),
                ('photo', models.CharField(max_length=100, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.counties')),
                ('fabricator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.fabricator')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.material')),
            ],
        ),
        migrations.AddField(
            model_name='fabricator',
            name='material_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.material'),
        ),
    ]
